### ISSUE TITLE
timeout !!!

### ISSUE THREAD

**Issue by trungthinhbo** [zcrossoverz/manga-lib#9]
Mình lấy dữ liệu nhiều chapters 1 lần, nên gặp lỗi `Navigation timeout of 30000 ms exceeded.` Bạn chỉ mình cách fix với ạ.
<img width="654" alt="Screen Shot 2023-08-02 at 15 00 29" src="https://github.com/zcrossoverz/manga-lib/assets/123989667/c7bad28b-a8bc-4493-8b57-e3155e919be4">

**Comment by zcrossoverz** [comment]
lỗi này là của do thư viện bên thứ 3 (puppeteer) nha bạn, mình đã update lại set timeout unlimited rồi nhé
